version: "3.7"
services:
    app:
        build:
            args:
                user: bcontartese
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: salepos
        container_name: salepos-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - salepos
    db:
        image: mysql:5.7
        container_name: salepos-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: salepos
            MYSQL_ROOT_PASSWORD: "!1passwordmuyfuerte!"
            MYSQL_PASSWORD: secret
            MYSQL_USER: salepos
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - salepos
    nginx:
        image: nginx:1.17-alpine
        container_name: salepos-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            -   salepos
networks:
    salepos:
        driver: bridge
